name: Publish Docker Image
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DATA }}

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DATA }} ghcr.io/heysokoly/heyview:main

      - name: Push Docker Image
        run: docker push ghcr.io/heysokoly/heyview:main
