name: Publish Docker Image
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ghcr.io/heysokoly/rview:main

      - name: Tag Docker Image
        run: docker tag rview ghcr.io/heysokoly/heyview:main

      - name: Push Docker Image
        run: docker push heysokoly/heyview:main
